apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudtask-config
  namespace: cloudtask
data:
  APP_ENV: development
  APP_PORT: "8000"
  LOG_LEVEL: INFO
  STORAGE_MODE: local
  LOCAL_UPLOADS_DIR: /tmp/cloudtask-uploads
  AWS_REGION: us-east-1
  FORCE_HTTPS: "false"
  TRUSTED_HOSTS: "localhost,127.0.0.1,cloudtask-api,*"
