apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtask-api
  namespace: cloudtask
  labels:
    app: cloudtask-api
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloudtask-api
  template:
    metadata:
      labels:
        app: cloudtask-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            capabilities:
              drop: ["ALL"]
          command:
            - sh
            - -c
            - until pg_isready -h cloudtask-db -U cloudtask -d cloudtask; do sleep 2; done
      containers:
        - name: api
          image: cloudtask-api:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: cloudtask-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cloudtask-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudtask-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
      securityContext:
        seccompProfile:
          type: RuntimeDefault
