apiVersion: v1
kind: Service
metadata:
  name: cloudtask-api
  namespace: cloudtask
  labels:
    app: cloudtask-api
spec:
  selector:
    app: cloudtask-api
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
